# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    master: # or 'main' if your default branch is named 'main'
      - step:
          name: Mirror to GitHub
          script:
            - echo "Mirroring reach-c-stack to GitHub"
            - git push --mirror https://Developer-i3PD:${GITHUB_TOKEN}@github.com/cygnus-technology/reach-c-stack.git
