/********************************************************************************************
 *    _ ____  ___             _         _     ___              _                        _
 *   (_)__ / | _ \_ _ ___  __| |_  _ __| |_  |   \ _____ _____| |___ _ __ _ __  ___ _ _| |_
 *   | ||_ \ |  _/ '_/ _ \/ _` | || / _|  _| | |) / -_) V / -_) / _ \ '_ \ '  \/ -_) ' \  _|
 *   |_|___/ |_| |_| \___/\__,_|\_,_\__|\__| |___/\___|\_/\___|_\___/ .__/_|_|_\___|_||_\__|
 *                                                                  |_|
 *                           -----------------------------------
 *                          Copyright i3 Product Development 2024
 *
 * MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * @file      definitions.c
 * @brief     A minimal implementation of Reach data access.  Auto-generated by a Python script.
 * @copyright 2023-2024 i3 Product Development. All Rights Reserved.
 *
 * Original Author: Chuck Peplinski
 * Script Author: Joseph Peplinski
 *
 *
 ********************************************************************************************/

#include "definitions.h"

#ifdef INCLUDE_WIFI_SERVICE

#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "i3_log.h"
#include "app_version.h"
#include "cr_stack.h"

// Extra includes and forward declarations here.
// User code start [W1]
// User code end [W1]


/**
* @brief   crcb_discover_wifi
* @details Retrieve the requested information about the WiFi 
 *         system. The discovery process may take some time the
 *         implementation can choose to return
 *         cr_ErrorCodes_INCOMPLETE to indicate that the
 *         discover command needs to be issued again until it
 *         succeeds. Other errors are reported via the result
 *         field.
* @param   request (input) Unused.
* @param   response (output) The requested info
* @return  returns cr_ErrorCodes_NO_ERROR or 
*          cr_ErrorCodes_INCOMPLETE. 
*/
int crcb_discover_wifi(const cr_DiscoverWiFi *request, 
                             cr_DiscoverWiFiResponse *response)
{
    (void)request;
    response->result = cr_ErrorCodes_NOT_IMPLEMENTED;
    // If you haven not just launched a scan, launch one.
    // If you don't yet have data, return cr_ErrorCodes_INCOMPLETE.
    // User code start [crcb_discover_wifi]
    // User code end [crcb_discover_wifi]
    return 0;
}

uint8_t sWiFi_index = 0;
/**
* @brief   crcb_get_wifi_count
* @return  The number of wifi access points available to the
*          the device.
*/    
int crcb_get_wifi_count()
{
    // User code start [crcb_get_wifi_count]
    // User code end [crcb_get_wifi_count]
    return NUM_WIFI_AP;
}

/**
* @brief   crcb_wifi_discover_reset
* @details The overriding implementation must reset a pointer 
*          into a table of the available wifi access points
*          such that the next call to
*          crcb_wifi_discover_next() will return the description
*          of this access point.
* @param   cid The ID to which the wifi table pointer 
*              should be reset.  0 for the first AP.
* @return  cr_ErrorCodes_NO_ERROR on success or a non-zero error like 
*          cr_ErrorCodes_INVALID_PARAMETER.
*/
int crcb_wifi_discover_reset(const uint32_t cid)
{
    if (cid >= NUM_WIFI_AP)
    {
        sWiFi_index = NUM_WIFI_AP;
        return cr_ErrorCodes_INVALID_ID;
    }
    // User code start [crcb_wifi_discover_reset]
    // User code end [crcb_wifi_discover_reset]
    return 0;
}

/**
* @brief   crcb_wifi_discover_next
* @details Gets the wifi description for the next wifi. 
*          The overriding implementation must post-increment its pointer into 
*          the wifi table.
* @param   cmd_desc Pointer to stack provided memory into which the 
*               wifi description is to be copied.
* @return  cr_ErrorCodes_NO_ERROR on success or cr_ErrorCodes_INVALID_PARAMETER 
*          if the last wifi has already been returned.
*/
int crcb_wifi_discover_next(cr_ConnectionDescription *conn_desc)
{
    if (sWiFi_index >= NUM_WIFI_AP)
        return cr_ErrorCodes_INVALID_ID;

    *conn_desc = wifi_desc[sWiFi_index];

    // User code start [crcb_wifi_discover_next]
    // User code end [crcb_wifi_discover_next]

    sWiFi_index++;
    return 0;
}

/**
* @brief   crcb_wifi_connection
* @details Establish or break a WiFi connection.
* @param   request (input) what needed to connect
* @param   response (output) result
* @return  returns zero or an error code
*/
int crcb_wifi_connection(const cr_WiFiConnectionRequest *request, 
                               cr_WiFiConnectionResponse *response)
{
    affirm(request);
    affirm(response);

    // User code start [crcb_wifi_connection]
    // User code end [crcb_wifi_connection]

    return 0;
}

// Local variables and functions here
// User code start [W2]
// User code end [W2]


#endif  // def INCLUDE_WIFI_SERVICE
